#!/usr/bin/env python3
"""Generate committed public country pages from the shared HTML template."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_PATH = REPOSITORY_ROOT / "src" / "pages" / "country.html"
COUNTRY_DATA_ROOT = REPOSITORY_ROOT / "src" / "data" / "countries"
OUTPUT_ROOT = REPOSITORY_ROOT / "src" / "countries"
GENERATED_MARKER = "<!-- Generated by scripts/generate-country-pages.py; do not edit. -->"
SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
REQUIRED_SECTION_FILES = (
    "best-months.json",
    "budget.json",
    "cuisine.json",
    "faqs.json",
    "inter-city-travel.json",
    "itinerary.json",
)


def required_text(value: object, field_name: str, source: Path) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{source}: {field_name} must be a non-empty string")
    return value.strip()


def load_published_countries() -> list[dict[str, str]]:
    countries: list[dict[str, str]] = []

    for country_path in sorted(COUNTRY_DATA_ROOT.glob("*/country.json")):
        data = json.loads(country_path.read_text(encoding="utf-8"))
        directory_slug = country_path.parent.name
        slug = required_text(data.get("slug"), "slug", country_path)

        if not SLUG_PATTERN.fullmatch(slug):
            raise ValueError(f"{country_path}: slug is not lowercase kebab-case")
        if slug != directory_slug:
            raise ValueError(
                f"{country_path}: slug {slug!r} does not match directory {directory_slug!r}"
            )
        if data.get("status") != "published":
            continue

        if not isinstance(data.get("visitedYear"), int):
            raise ValueError(f"{country_path}: visitedYear must be an integer")

        for filename in REQUIRED_SECTION_FILES:
            section_path = country_path.parent / filename
            if not section_path.is_file():
                raise ValueError(f"{country_path}: missing required {filename}")
            json.loads(section_path.read_text(encoding="utf-8"))

        seo = data.get("seo")
        if not isinstance(seo, dict):
            raise ValueError(f"{country_path}: seo must be an object")

        countries.append(
            {
                "slug": slug,
                "name": required_text(data.get("name"), "name", country_path),
                "overview": required_text(
                    data.get("overview"), "overview", country_path
                ),
                "seo_title": required_text(seo.get("title"), "seo.title", country_path),
                "seo_description": required_text(
                    seo.get("description"), "seo.description", country_path
                ),
            }
        )

    return countries


def render_country_page(template: str, country: dict[str, str]) -> str:
    replacements = {
        "{{countrySlug}}": country["slug"],
        "{{countryName}}": html.escape(country["name"], quote=True),
        "{{countryOverview}}": html.escape(country["overview"], quote=True),
        "{{seoTitle}}": html.escape(country["seo_title"], quote=True),
        "{{seoDescription}}": html.escape(
            country["seo_description"], quote=True
        ),
    }

    rendered = template
    for token, value in replacements.items():
        if token not in rendered:
            raise ValueError(f"{TEMPLATE_PATH}: missing required token {token}")
        rendered = rendered.replace(token, value)

    if re.search(r"{{[A-Za-z][A-Za-z0-9]*}}", rendered):
        raise ValueError(f"{TEMPLATE_PATH}: contains an unreplaced template token")

    return f"{GENERATED_MARKER}\n{rendered}"


def generated_pages() -> dict[Path, str]:
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    return {
        OUTPUT_ROOT / f"{country['slug']}.html": render_country_page(template, country)
        for country in load_published_countries()
    }


def stale_generated_pages(expected_paths: set[Path]) -> list[Path]:
    if not OUTPUT_ROOT.exists():
        return []

    stale: list[Path] = []
    for path in OUTPUT_ROOT.glob("*.html"):
        if path in expected_paths:
            continue
        if path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            stale.append(path)
    return stale


def check_pages(pages: dict[Path, str]) -> int:
    failures: list[str] = []

    for path, expected in pages.items():
        if not path.exists():
            failures.append(f"missing {path.relative_to(REPOSITORY_ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"outdated {path.relative_to(REPOSITORY_ROOT)}")

    failures.extend(
        f"stale {path.relative_to(REPOSITORY_ROOT)}"
        for path in stale_generated_pages(set(pages))
    )

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1

    print(f"Country pages are up to date ({len(pages)} generated).")
    return 0


def write_pages(pages: dict[Path, str]) -> None:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    for path, content in pages.items():
        path.write_text(content, encoding="utf-8")
        print(f"generated {path.relative_to(REPOSITORY_ROOT)}")

    for path in stale_generated_pages(set(pages)):
        path.unlink()
        print(f"removed stale {path.relative_to(REPOSITORY_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated pages without changing files",
    )
    options = parser.parse_args()

    try:
        pages = generated_pages()
        if not pages:
            raise ValueError("No published countries were found")
        if options.check:
            return check_pages(pages)
        write_pages(pages)
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"country page generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
